"""Helper functions and constants."""
from pathlib import Path
import warnings

import pandas as pd
import numpy as np

PROJECT_ROOT = Path.cwd()


def cliff_delta(X, Y):
    """Calculate the effect size using the Cliff's delta."""
    lx = len(X)
    ly = len(Y)
    mat = np.zeros((lx, ly))
    for i in range(0, lx):
        for j in range(0, ly):
            if X[i] > Y[j]:
                mat[i, j] = 1
            elif Y[j] > X[i]:
                mat[i, j] = -1

    return (np.sum(mat)) / (lx * ly)


def load_dataset(demographic_path, ids_path, freesurfer_path):
    """Load dataset."""
    demographic_data = load_demographic_data(demographic_path, ids_path)

    freesurfer_df = pd.read_csv(freesurfer_path)

    dataset_df = pd.merge(freesurfer_df, demographic_data, on='IID')

    return dataset_df


def load_demographic_data(demographic_path, ids_path):
    """Load dataset using selected ids."""

    demographic_df = pd.read_csv(demographic_path)
    demographic_df = demographic_df.dropna()

    print(ids_path)

    ids_df = pd.read_csv(ids_path, usecols=['IID'])

    if 'Run_ID' in demographic_df.columns:
        demographic_df['uid'] = demographic_df['participant_id'] + '_' + demographic_df['Session_ID'] + '_run-' + \
                                demographic_df['Run_ID'].apply(str)

        ids_df['uid'] = ids_df['IID'].str.split('_').str[0] + '_' + ids_df['IID'].str.split('_').str[1]+ '_' + ids_df['IID'].str.split('_').str[2]

        dataset_df = pd.merge(ids_df, demographic_df, on='uid')
        dataset_df = dataset_df.drop(columns=['uid'])

    elif 'Session_ID' in demographic_df.columns:
        demographic_df['uid'] = demographic_df['participant_id'] + '_' + demographic_df['Session_ID']

        ids_df['uid'] = ids_df['IID'].str.split('_').str[0] + '_' + ids_df['IID'].str.split('_').str[1]

        dataset_df = pd.merge(ids_df, demographic_df, on='uid')
        dataset_df = dataset_df.drop(columns=['uid'])

    else:
        ids_df['participant_id'] = ids_df['IID']
        # print('ids_df:', ids_df)
        # print('demographic_df:', demographic_df)
        dataset_df = pd.merge(ids_df, demographic_df, on='IID')

    return dataset_df


#COLUMNS_NAME = [(lambda x: 'C'+ str(x))(y) for y in list(range(5,105))]
COLUMNS_NAME = ['Precentral_L',
'Precentral_R',
'Frontal_Sup_L',
'Frontal_Sup_R',
'Frontal_Sup_Orb_L',
'Frontal_Sup_Orb_R',
'Frontal_Mid_L',
'Frontal_Mid_R',
'Frontal_Mid_Orb_L',
'Frontal_Mid_Orb_R',
'Frontal_Inf_Oper_L',
'Frontal_Inf_Oper_R',
'Frontal_Inf_Tri_L',
'Frontal_Inf_Tri_R',
'Frontal_Inf_Orb_L',
'Frontal_Inf_Orb_R',
'Rolandic_Oper_L',
'Rolandic_Oper_R',
'Supp_Motor_Area_L',
'Supp_Motor_Area_R',
'Olfactory_L',
'Olfactory_R',
'Frontal_Sup_Medial_L',
'Frontal_Sup_Medial_R',
'Frontal_Med_Orb_L',
'Frontal_Med_Orb_R',
'Rectus_L',
'Rectus_R',
'Insula_L',
'Insula_R',
'Cingulum_Ant_L',
'Cingulum_Ant_R',
'Cingulum_Mid_L',
'Cingulum_Mid_R',
'Cingulum_Post_L',
'Cingulum_Post_R',
'Hippocampus_L',
'Hippocampus_R',
'ParaHippocampal_L',
'ParaHippocampal_R',
'Amygdala_L',
'Amygdala_R',
'Calcarine_L',
'Calcarine_R',
'Cuneus_L',
'Cuneus_R',
'Lingual_L',
'Lingual_R',
'Occipital_Sup_L',
'Occipital_Sup_R',
'Occipital_Mid_L',
'Occipital_Mid_R',
'Occipital_Inf_L',
'Occipital_Inf_R',
'Fusiform_L',
'Fusiform_R',
'Postcentral_L',
'Postcentral_R',
'Parietal_Sup_L',
'Parietal_Sup_R',
'Parietal_Inf_L',
'Parietal_Inf_R',
'SupraMarginal_L',
'SupraMarginal_R',
'Angular_L',
'Angular_R',
'Precuneus_L',
'Precuneus_R',
'Paracentral_Lobule_L',
'Paracentral_Lobule_R',
'Caudate_L',
'Caudate_R',
'Putamen_L',
'Putamen_R',
'Pallidum_L',
'Pallidum_R',
'Thalamus_L',
'Thalamus_R',
'Heschl_L',
'Heschl_R',
'Temporal_Sup_L',
'Temporal_Sup_R',
'Temporal_Pole_Sup_L',
'Temporal_Pole_Sup_R',
'Temporal_Mid_L',
'Temporal_Mid_R',
'Temporal_Pole_Mid_L',
'Temporal_Pole_Mid_R',
'Temporal_Inf_L',
'Temporal_Inf_R',
]


COLUMNS_NAME_VBM = ['MNI_Amygdala_L',
'MNI_Amygdala_R',
'MNI_Angular_L',
'MNI_Angular_R',
'MNI_Calcarine_L',
'MNI_Calcarine_R',
'MNI_Caudate_L',
'MNI_Caudate_R',
'MNI_Cingulum_Ant_L',
'MNI_Cingulum_Ant_R',
'MNI_Cingulum_Mid_L',
'MNI_Cingulum_Mid_R',
'MNI_Cingulum_Post_L',
'MNI_Cingulum_Post_R',
'MNI_Cuneus_L',
'MNI_Cuneus_R',
'MNI_Frontal_Inf_Oper_L',
'MNI_Frontal_Inf_Oper_R',
'MNI_Frontal_Inf_Orb_L',
'MNI_Frontal_Inf_Orb_R',
'MNI_Frontal_Inf_Tri_L',
'MNI_Frontal_Inf_Tri_R',
'MNI_Frontal_Med_Orb_L',
'MNI_Frontal_Med_Orb_R',
'MNI_Frontal_Mid_L',
'MNI_Frontal_Mid_R',
'MNI_Frontal_Mid_Orb_L',
'MNI_Frontal_Mid_Orb_R',
'MNI_Frontal_Sup_L',
'MNI_Frontal_Sup_R',
'MNI_Frontal_Sup_Medial_L',
'MNI_Frontal_Sup_Medial_R',
'MNI_Frontal_Sup_Orb_L',
'MNI_Frontal_Sup_Orb_R',
'MNI_Fusiform_L',
'MNI_Fusiform_R',
'MNI_Heschl_L',
'MNI_Heschl_R',
'MNI_Hippocampus_L',
'MNI_Hippocampus_R',
'MNI_Insula_L',
'MNI_Insula_R',
'MNI_Lingual_L',
'MNI_Lingual_R',
'MNI_Occipital_Inf_L',
'MNI_Occipital_Inf_R',
'MNI_Occipital_Mid_L',
'MNI_Occipital_Mid_R',
'MNI_Occipital_Sup_L',
'MNI_Occipital_Sup_R',
'MNI_Olfactory_L',
'MNI_Olfactory_R',
'MNI_Pallidum_L',
'MNI_Pallidum_R',
'MNI_ParaHippocampal_L',
'MNI_ParaHippocampal_R',
'MNI_Paracentral_Lobule_L',
'MNI_Paracentral_Lobule_R',
'MNI_Parietal_Inf_L',
'MNI_Parietal_Inf_R',
'MNI_Parietal_Sup_L',
'MNI_Parietal_Sup_R',
'MNI_Postcentral_L',
'MNI_Postcentral_R',
'MNI_Precentral_L',
'MNI_Precentral_R',
'MNI_Precuneus_L',
'MNI_Precuneus_R',
'MNI_Putamen_L',
'MNI_Putamen_R',
'MNI_Rectus_L',
'MNI_Rectus_R',
'MNI_Rolandic_Oper_L',
'MNI_Rolandic_Oper_R',
'MNI_Supp_Motor_Area_L',
'MNI_Supp_Motor_Area_R',
'MNI_SupraMarginal_L',
'MNI_SupraMarginal_R',
'MNI_Temporal_Inf_L',
'MNI_Temporal_Inf_R',
'MNI_Temporal_Mid_L',
'MNI_Temporal_Mid_R',
'MNI_Temporal_Pole_Mid_L',
'MNI_Temporal_Pole_Mid_R',
'MNI_Temporal_Pole_Sup_L',
'MNI_Temporal_Pole_Sup_R',
'MNI_Temporal_Sup_L',
'MNI_Temporal_Sup_R',
'MNI_Thalamus_L',
'MNI_Thalamus_R',
]

COLUMNS_NAME_SNP = ['rs4575098',
'rs6656401',
'rs2093760',
'rs4844610',
'rs4663105',
'rs6733839',
'rs10933431',
'rs35349669',
'rs6448453',
'rs190982',
'rs9271058',
'rs9473117',
'rs9381563',
'rs10948363',
'rs2718058',
'rs4723711',
'rs1859788',
'rs1476679',
'rs12539172',
'rs10808026',
'rs7810606',
'rs11771145',
'rs28834970',
'rs73223431',
'rs4236673',
'rs9331896',
'rs11257238',
'rs7920721',
'rs3740688',
'rs10838725',
'rs983392',
'rs7933202',
'rs2081545',
'rs867611',
'rs10792832',
'rs3851179',
'rs17125924',
'rs17125944',
'rs10498633',
'rs12881735',
'rs12590654',
'rs442495',
'rs59735493',
'rs113260531',
'rs28394864',
'rs111278892',
'rs3752246',
'rs4147929',
'rs41289512',
'rs3865444',
'rs6024870',
'rs6014724',
'rs7274581',
'rs429358',
]

# COLUMNS_NAME = [ 'LH_Vis_1',
#                 'LH_Vis_2',
#                 'LH_Vis_3',
#                 'LH_Vis_4',
#                 'LH_Vis_5',
#                 'LH_Vis_6',
#                 'LH_Vis_7',
#                 'LH_Vis_8',
#                 'LH_Vis_9',
#                 'LH_SomMot_1',
#                 'LH_SomMot_2',
#                 'LH_SomMot_3',
#                 'LH_SomMot_4',
#                 'LH_SomMot_5',
#                 'LH_SomMot_6',
#                 'LH_DorsAttn_Post_1',
#                 'LH_DorsAttn_Post_2',
#                 'LH_DorsAttn_Post_3',
#                 'LH_DorsAttn_Post_4',
#                 'LH_DorsAttn_Post_5',
#                 'LH_DorsAttn_Post_6',
#                 'LH_DorsAttn_FEF_1',
#                 'LH_DorsAttn_FEF_2',
#                 'LH_SalVentAttn_ParOper_1',
#                 'LH_SalVentAttn_FrOper_1',
#                 'LH_SalVentAttn_FrOper_2',
#                 'LH_SalVentAttn_PFCl_1',
#                 'LH_SalVentAttn_Med_1',
#                 'LH_SalVentAttn_Med_2',
#                 'LH_SalVentAttn_Med_3',
#                 'LH_Limbic_OFC_1',
#                 'LH_Limbic_TempPole_1',
#                 'LH_Limbic_TempPole_2',
#                 'LH_Cont_Par_1',
#                 'LH_Cont_PFCl_1',
#                 'LH_Cont_pCun_1',
#                 'LH_Cont_Cing_1',
#                 'LH_Default_Temp_1',
#                 'LH_Default_Temp_2',
#                 'LH_Default_Temp_3',
#                 'LH_Default_Temp_4',
#                 'LH_Default_PFC_1',
#                 'LH_Default_PFC_2',
#                 'LH_Default_PFC_3',
#                 'LH_Default_PFC_4',
#                 'LH_Default_PFC_5',
#                 'LH_Default_PFC_6',
#                 'LH_Default_PFC_7',
#                 'LH_Default_PCC_1',
#                 'LH_Default_PCC_2',
#                 'RH_Vis_1',
#                 'RH_Vis_2',
#                 'RH_Vis_3',
#                 'RH_Vis_4',
#                 'RH_Vis_5',
#                 'RH_Vis_6',
#                 'RH_Vis_7',
#                 'RH_Vis_8',
#                 'RH_SomMot_1',
#                 'RH_SomMot_2',
#                 'RH_SomMot_3',
#                 'RH_SomMot_4',
#                 'RH_SomMot_5',
#                 'RH_SomMot_6',
#                 'RH_SomMot_7',
#                 'RH_SomMot_8',
#                 'RH_DorsAttn_Post_1',
#                 'RH_DorsAttn_Post_2',
#                 'RH_DorsAttn_Post_3',
#                 'RH_DorsAttn_Post_4',
#                 'RH_DorsAttn_Post_5',
#                 'RH_DorsAttn_FEF_1',
#                 'RH_DorsAttn_FEF_2',
#                 'RH_SalVentAttn_TempOccPar_1',
#                 'RH_SalVentAttn_TempOccPar_2',
#                 'RH_SalVentAttn_FrOper_1',
#                 'RH_SalVentAttn_Med_1',
#                 'RH_SalVentAttn_Med_2',
#                 'RH_Limbic_OFC_1',
#                 'RH_Limbic_TempPole_1',
#                 'RH_Cont_Par_1',
#                 'RH_Cont_Par_2',
#                 'RH_Cont_PFCl_1',
#                 'RH_Cont_PFCl_2',
#                 'RH_Cont_PFCl_3',
#                 'RH_Cont_PFCl_4',
#                 'RH_Cont_PFCmp_1',
#                 'RH_Cont_PFCmp_2',
#                 'RH_Cont_PFCmp_3',
#                 'RH_Default_Par_1',
#                 'RH_Default_Temp_1',
#                 'RH_Default_Temp_2',
#                 'RH_Default_Temp_3',
#                 'RH_Default_PFCv_1',
#                 'RH_Default_PFCv_2',
#                 'RH_Default_PFCm_1',
#                 'RH_Default_PFCm_2',
#                 'RH_Default_PFCm_3',
#                 'RH_Default_PCC_1',
#                 'RH_Default_PCC_2' ]

# COLUMNS_NAME = ['Left Lateral Ventricle',
#                 'Left Inf Lat Vent',
#                 'Left Cerebellum White Matter',
#                 'Left Cerebellum Cortex',
#                 'Left Thalamus Proper',
#                 'Left Caudate',
#                 'Left Putamen',
#                 'Left Pallidum',
#                 'rd Ventricle',
#                 'th Ventricle',
#                 'Brain Stem',
#                 'Left Hippocampus',
#                 'Left Amygdala',
#                 'CSF',
#                 'Left Accumbens area',
#                 'Left VentralDC',
#                 'Right Lateral Ventricle',
#                 'Right Inf Lat Vent',
#                 'Right Cerebellum White Matter',
#                 'Right Cerebellum Cortex',
#                 'Right Thalamus Proper',
#                 'Right Caudate',
#                 'Right Putamen',
#                 'Right Pallidum',
#                 'Right Hippocampus',
#                 'Right Amygdala',
#                 'Right Accumbens area',
#                 'Right VentralDC',
#                 'CC Posterior',
#                 'CC Mid Posterior',
#                 'CC Central',
#                 'CC Mid Anterior',
#                 'CC Anterior',
#                 'lh bankssts volume',
#                 'lh caudalanteriorcingulate volume',
#                 'lh caudalmiddlefrontal volume',
#                 'lh cuneus volume',
#                 'lh entorhinal volume',
#                 'lh fusiform volume',
#                 'lh inferiorparietal volume',
#                 'lh inferiortemporal volume',
#                 'lh isthmuscingulate volume',
#                 'lh lateraloccipital volume',
#                 'lh lateralorbitofrontal volume',
#                 'lh lingual volume',
#                 'lh medialorbitofrontal volume',
#                 'lh middletemporal volume',
#                 'lh parahippocampal volume',
#                 'lh paracentral volume',
#                 'lh parsopercularis volume',
#                 'lh parsorbitalis volume',
#                 'lh parstriangularis volume',
#                 'lh pericalcarine volume',
#                 'lh postcentral volume',
#                 'lh posteriorcingulate volume',
#                 'lh precentral volume',
#                 'lh precuneus volume',
#                 'lh rostralanteriorcingulate volume',
#                 'lh rostralmiddlefrontal volume',
#                 'lh superiorfrontal volume',
#                 'lh superiorparietal volume',
#                 'lh superiortemporal volume',
#                 'lh supramarginal volume',
#                 'lh frontalpole volume',
#                 'lh temporalpole volume',
#                 'lh transversetemporal volume',
#                 'lh insula volume',
#                 'rh bankssts volume',
#                 'rh caudalanteriorcingulate volume',
#                 'rh caudalmiddlefrontal volume',
#                 'rh cuneus volume',
#                 'rh entorhinal volume',
#                 'rh fusiform volume',
#                 'rh inferiorparietal volume',
#                 'rh inferiortemporal volume',
#                 'rh isthmuscingulate volume',
#                 'rh lateraloccipital volume',
#                 'rh lateralorbitofrontal volume',
#                 'rh lingual volume',
#                 'rh medialorbitofrontal volume',
#                 'rh middletemporal volume',
#                 'rh parahippocampal volume',
#                 'rh paracentral volume',
#                 'rh parsopercularis volume',
#                 'rh parsorbitalis volume',
#                 'rh parstriangularis volume',
#                 'rh pericalcarine volume',
#                 'rh postcentral volume',
#                 'rh posteriorcingulate volume',
#                 'rh precentral volume',
#                 'rh precuneus volume',
#                 'rh rostralanteriorcingulate volume',
#                 'rh rostralmiddlefrontal volume',
#                 'rh superiorfrontal volume',
#                 'rh superiorparietal volume',
#                 'rh superiortemporal volume',
#                 'rh supramarginal volume',
#                 'rh frontalpole volume',
#                 'rh temporalpole volume',
#                 'rh transversetemporal volume',
#                 'rh insula volume']


# COLUMNS_NAME = ['Left-Lateral-Ventricle',
#                 'Left-Inf-Lat-Vent',
#                 'Left-Cerebellum-White-Matter',
#                 'Left-Cerebellum-Cortex',
#                 'Left-Thalamus-Proper',
#                 'Left-Caudate',
#                 'Left-Putamen',
#                 'Left-Pallidum',
#                 '3rd-Ventricle',
#                 '4th-Ventricle',
#                 'Brain-Stem',
#                 'Left-Hippocampus',
#                 'Left-Amygdala',
#                 'CSF',
#                 'Left-Accumbens-area',
#                 'Left-VentralDC',
#                 'Right-Lateral-Ventricle',
#                 'Right-Inf-Lat-Vent',
#                 'Right-Cerebellum-White-Matter',
#                 'Right-Cerebellum-Cortex',
#                 'Right-Thalamus-Proper',
#                 'Right-Caudate',
#                 'Right-Putamen',
#                 'Right-Pallidum',
#                 'Right-Hippocampus',
#                 'Right-Amygdala',
#                 'Right-Accumbens-area',
#                 'Right-VentralDC',
#                 'CC_Posterior',
#                 'CC_Mid_Posterior',
#                 'CC_Central',
#                 'CC_Mid_Anterior',
#                 'CC_Anterior',
#                 'lh_bankssts_volume',
#                 'lh_caudalanteriorcingulate_volume',
#                 'lh_caudalmiddlefrontal_volume',
#                 'lh_cuneus_volume',
#                 'lh_entorhinal_volume',
#                 'lh_fusiform_volume',
#                 'lh_inferiorparietal_volume',
#                 'lh_inferiortemporal_volume',
#                 'lh_isthmuscingulate_volume',
#                 'lh_lateraloccipital_volume',
#                 'lh_lateralorbitofrontal_volume',
#                 'lh_lingual_volume',
#                 'lh_medialorbitofrontal_volume',
#                 'lh_middletemporal_volume',
#                 'lh_parahippocampal_volume',
#                 'lh_paracentral_volume',
#                 'lh_parsopercularis_volume',
#                 'lh_parsorbitalis_volume',
#                 'lh_parstriangularis_volume',
#                 'lh_pericalcarine_volume',
#                 'lh_postcentral_volume',
#                 'lh_posteriorcingulate_volume',
#                 'lh_precentral_volume',
#                 'lh_precuneus_volume',
#                 'lh_rostralanteriorcingulate_volume',
#                 'lh_rostralmiddlefrontal_volume',
#                 'lh_superiorfrontal_volume',
#                 'lh_superiorparietal_volume',
#                 'lh_superiortemporal_volume',
#                 'lh_supramarginal_volume',
#                 'lh_frontalpole_volume',
#                 'lh_temporalpole_volume',
#                 'lh_transversetemporal_volume',
#                 'lh_insula_volume',
#                 'rh_bankssts_volume',
#                 'rh_caudalanteriorcingulate_volume',
#                 'rh_caudalmiddlefrontal_volume',
#                 'rh_cuneus_volume',
#                 'rh_entorhinal_volume',
#                 'rh_fusiform_volume',
#                 'rh_inferiorparietal_volume',
#                 'rh_inferiortemporal_volume',
#                 'rh_isthmuscingulate_volume',
#                 'rh_lateraloccipital_volume',
#                 'rh_lateralorbitofrontal_volume',
#                 'rh_lingual_volume',
#                 'rh_medialorbitofrontal_volume',
#                 'rh_middletemporal_volume',
#                 'rh_parahippocampal_volume',
#                 'rh_paracentral_volume',
#                 'rh_parsopercularis_volume',
#                 'rh_parsorbitalis_volume',
#                 'rh_parstriangularis_volume',
#                 'rh_pericalcarine_volume',
#                 'rh_postcentral_volume',
#                 'rh_posteriorcingulate_volume',
#                 'rh_precentral_volume',
#                 'rh_precuneus_volume',
#                 'rh_rostralanteriorcingulate_volume',
#                 'rh_rostralmiddlefrontal_volume',
#                 'rh_superiorfrontal_volume',
#                 'rh_superiorparietal_volume',
#                 'rh_superiortemporal_volume',
#                 'rh_supramarginal_volume',
#                 'rh_frontalpole_volume',
#                 'rh_temporalpole_volume',
#                 'rh_transversetemporal_volume',
#                 'rh_insula_volume']